/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.facturacion.vista;

import com.mycompany.facturacion.db.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FmrMercancia extends javax.swing.JFrame {

    /**
     * Creates new form FmrMercancia
     */
    public FmrMercancia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        radioServicio = new javax.swing.JRadioButton();
        radioProducto = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionCompleta = new javax.swing.JTextArea();
        txtHorario = new javax.swing.JTextField();
        txtNumTecnicos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        cbxUnidadMedida = new javax.swing.JComboBox<>();
        btn_Guardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Gestion de Mercancia");

        jLabel2.setText("Codigo");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Precio");

        radioServicio.setText("Servicio");
        radioServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioServicioActionPerformed(evt);
            }
        });

        radioProducto.setText("Producto");
        radioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioProductoActionPerformed2(evt);
            }
        });

        jLabel5.setText("Horario");

        jLabel6.setText("N. Tecnicos");

        jLabel7.setText("Desc Completa");

        txtDescripcionCompleta.setColumns(20);
        txtDescripcionCompleta.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionCompleta);

        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });

        jLabel8.setText("Peso");

        cbxUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidad Medida", "UND", "KL", "GR", " " }));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed2(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHorario)
                                    .addComponent(txtNumTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtNombreCompleto)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radioServicio))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radioProducto)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49))
                                    .addComponent(cbxUnidadMedida, 0, 178, Short.MAX_VALUE))
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btn_Guardar))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioServicio)
                    .addComponent(radioProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNumTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MerActionPerformed
    txtCodigo.transferFocus();       // TODO add your handling code here:
    
    }//GEN-LAST:event_txt_MerActionPerformed

    private void txt_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NomActionPerformed
    txtNombreCompleto.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NomActionPerformed

    private void txt_PreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PreActionPerformed
    txtPrecio.transferFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PreActionPerformed

    private void txt_UnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UnidadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_UnidadActionPerformed

    private void radioServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioServicioActionPerformed
        // TODO add your handling code here:
            this.txtPeso.enable(false);
            this.cbxUnidadMedida.enable(false);
            this.txtHorario.enable(true);
            this.txtNumTecnicos.enable(true);
            this.txtDescripcionCompleta.enable(true);
            this.radioProducto.setSelected(false);
        
    }//GEN-LAST:event_radioServicioActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void radioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
            this.txtPeso.enable(true);
            this.cbxUnidadMedida.enable(true);
            this.txtHorario.enable(false);
            this.txtNumTecnicos.enable(false);
            this.txtDescripcionCompleta.enable(false);
            this.radioServicio.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
       Conexion cc = new Conexion();
       Connection cn = cc.getConnection();
       String mercancia,nombre;
       Double precio;
       Integer peso;
       String unidad;
       String horario;
       Integer cantidad;
       String descripcion;
       mercancia=txtCodigo.getText();
       nombre=txtNombreCompleto.getText();
       precio=Double.parseDouble(txtPrecio.getText());
       peso=Integer.parseInt(txtPeso.getText());
       unidad=cbxUnidadMedida.getSelectedItem().toString();
       horario=txtHorario.getText();
       cantidad=Integer.parseInt(txtNumTecnicos.getText());
       descripcion=txtDescripcionCompleta.getText();
       boolean esServicio=radioServicio.isSelected();
       
       
      String sql="INSERT INTO mercancia(idMercancia, nombre, precio, esServicio, descripcionCompleta, numeroTecnicos, horarioServicio, peso, unidadMedidad)VALUES(?,?,?,?,?,?,?,?,?) ";
       
          try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,mercancia);
            pst.setString(2,nombre);
            pst.setDouble(3,precio);
            pst.setBoolean(4,esServicio);
            pst.setString(5,descripcion);
            pst.setInt(6,cantidad);
            pst.setString(7,horario);
            pst.setInt(8,peso);
            pst.setString(9,unidad);
            
            
            pst.executeUpdate();
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"Mercancia Guardada con Exito");
                
            }
       }catch(Exception e){
           System.err.println(e);
       }
       
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void radioProductoActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioProductoActionPerformed2
        // TODO add your handling code here:
                // TODO add your handling code here:
            this.txtPeso.enable(true);
            this.cbxUnidadMedida.enable(true);
            this.txtHorario.enable(false);
            this.txtNumTecnicos.enable(false);
            this.txtDescripcionCompleta.enable(false);
            this.radioServicio.setSelected(false);
    }//GEN-LAST:event_radioProductoActionPerformed2

    private void btn_GuardarActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed2
        // TODO add your handling code here:
         Conexion cc = new Conexion();
       Connection cn = cc.getConnection();
       String mercancia,nombre;
       Double precio;
       Integer peso;
       String unidad;
       String horario;
       Integer cantidad;
       String descripcion;
       mercancia=txtCodigo.getText();
       nombre=txtNombreCompleto.getText();
       precio=Double.parseDouble(txtPrecio.getText());
       peso=Integer.parseInt(txtPeso.getText());
       unidad=cbxUnidadMedida.getSelectedItem().toString();
       horario=txtHorario.getText();
       cantidad=Integer.parseInt(txtNumTecnicos.getText());
       descripcion=txtDescripcionCompleta.getText();
       boolean esServicio=radioServicio.isSelected();
       
       
      String sql="INSERT INTO mercancia(idMercancia, nombre, precio, esServicio, descripcionCompleta, numeroTecnicos, horarioServicio, peso, unidadMedidad)VALUES(?,?,?,?,?,?,?,?,?) ";
       
          try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,mercancia);
            pst.setString(2,nombre);
            pst.setDouble(3,precio);
            pst.setBoolean(4,esServicio);
            pst.setString(5,descripcion);
            pst.setInt(6,cantidad);
            pst.setString(7,horario);
            pst.setInt(8,peso);
            pst.setString(9,unidad);
            
            
            pst.executeUpdate();
            int n=pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null,"Mercancia Guardada con Exito");
                
            }
       }catch(SQLException e){
           System.err.println(e);
       }
    }//GEN-LAST:event_btn_GuardarActionPerformed2

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrMercancia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrMercancia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbxUnidadMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioProducto;
    private javax.swing.JRadioButton radioServicio;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDescripcionCompleta;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNumTecnicos;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
